events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Redireciona chamadas /api para o Spring Boot
        location /api/ {
            proxy_pass http://backend:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redireciona todo o resto para o React
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Necessário para o Hot Reload do Vite funcionar
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }


        location /swagger-ui/ {
            proxy_pass http://backend:8080/swagger-ui/;
            proxy_set_header Host $host;
        }

        location /v3/api-docs {
            proxy_pass http://backend:8080/v3/api-docs;
        }
    }
}

